### ISSUE TITLE
There are several references to the folder "path_planning_utils" in the code, but I can't seem to find the folder, and I'm not sure if it's just me! But it doesn't seem to affect how the project compiles and runs.

### ISSUE THREAD

**Issue by Maxianzhai** [tedhuang96/PNGNav#1]
Hi,Huang. There are several references to the folder "path_planning_utils" in the code, but I can't seem to find the folder, and I'm not sure if it's just me! But it doesn't seem to affect how the project compiles and runs.
Here are the code files that I think are problematic 
PNGNav/src/png_navigation/src/png_navigation/path_planning_classes/nirrt_star_png_c_2d.py 
PNGNav/src/png_navigation/src/png_navigation/datasets/planning_problem_utils_2d.py
PNGNav/src/png_navigation/src/png_navigation/datasets/rectangle_env_2d.py

**Comment by tedhuang96** [comment]
Hi, thank you for pointing this out! You are right that `path_planning_utils/` is not included in this repo. Since I first built training/evaluation scripts for [NIRRT*](https://github.com/tedhuang96/nirrt_star), and then built `png_navigation` ROS package by moving part of scripts here, there will be some inconsistency on the code. The files you pointed out here are used in [NIRRT*](https://github.com/tedhuang96/nirrt_star), but not used in PNGNav. 

To explain each file,
1. PNGNav/src/png_navigation/src/png_navigation/path_planning_classes/nirrt_star_png_c_2d.py

`nirrt_star_png_c_2d.py` is the source file for NIRRT* with Point-based Network Guidance with Neural Connect. We did not use this file in `png_navigation`, because in nirrt_star_c.launch, this is done by these two ROS node files 
https://github.com/tedhuang96/PNGNav/blob/d7f8a4d53164dc9e9ae14b743b10ef0a7df19bcb/src/png_navigation/launch/nirrt_star_c.launch#L4-L5
which just needs to import `nirrt_star_png_2d`.
https://github.com/tedhuang96/PNGNav/blob/d7f8a4d53164dc9e9ae14b743b10ef0a7df19bcb/src/png_navigation/scripts/nirrt_star_node.py#L8

2. PNGNav/src/png_navigation/src/png_navigation/datasets/planning_problem_utils_2d.py
This is a file used in evaluation of each path planning method in simulation experiments.

3. PNGNav/src/png_navigation/src/png_navigation/datasets/rectangle_env_2d.py
This is a file used for generating the raw data for random world (2D) simulation experiments.

`path_planning_utils` will be included in [NIRRT*](https://github.com/tedhuang96/nirrt_star). Also note that the files mentioned here may be renamed since we have been organizing/cleaning the code for open sourcing [NIRRT*](https://github.com/tedhuang96/nirrt_star).

I will check and clean these deprecated files in the next commit. Thank you for pointing them out!

**Comment by tedhuang96** [comment]
https://github.com/tedhuang96/PNGNav/commit/623e3e5085c6850d1b3f6292a6f1baab1e6045a4
https://github.com/tedhuang96/PNGNav/releases/tag/v1.0.1
